spring.application.name=inventario
server.port=8080

# JWT
jwt.secret=${JWT_SECRET:YmFzZTY0RW5jb2RlZFNlY3JldEtleUZvckpXVApXb3JraW5nUHJvamVjdA==}
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
